Repository woocommerce/storefront, pull requests merged in 2018-03, with the labels that each got.

#669 Mobile menu enhancement
  assets/css/base/_base.scss
  assets/js/navigation.js
  inc/class-storefront.php
Labels: Accessibility, Status: Approved, Type: Enhancement

#763 Add Style Linting
  .stylelintrc
  Gruntfile.js
  assets/css/admin/admin.scss
  assets/css/admin/customizer/customizer.scss
  assets/css/admin/plugin-install.scss
  assets/css/admin/welcome-screen/welcome.scss
  assets/css/base/_base.scss
  assets/css/base/_layout.scss
  assets/css/base/icons.scss
  assets/css/sass/utils/_mixins.scss
  assets/css/sass/utils/_variables.scss
  assets/css/woocommerce/extensions/ajax-layered-nav.scss
  assets/css/woocommerce/extensions/bookings.scss
  assets/css/woocommerce/extensions/composite-products.scss
  assets/css/woocommerce/extensions/deposits.scss
  assets/css/woocommerce/extensions/memberships.scss
  assets/css/woocommerce/extensions/photography.scss
  assets/css/woocommerce/extensions/product-reviews-pro.scss
  assets/css/woocommerce/extensions/ship-multiple-addresses.scss
  assets/css/woocommerce/extensions/variation-swatches.scss
  assets/css/woocommerce/extensions/wishlists.scss
  assets/css/woocommerce/woocommerce.scss
  package.json
Labels: Status: Approved, Type: Enhancement

#797 Style other action buttons in the widget cart
  assets/css/woocommerce/woocommerce.scss
Labels: Status: Approved

#796 Internet Explorer 11 JS compatibility tweaks
  assets/js/homepage.js
  assets/js/navigation.js
Labels: Status: Approved

#794 Apply styles only to author section in entry meta
  assets/css/base/_base.scss
Labels: Status: Approved

#779 Remove columns wrapper and add legacy support
  Gruntfile.js
  assets/css/woocommerce/woocommerce-legacy.scss
  assets/css/woocommerce/woocommerce.scss
  inc/woocommerce/class-storefront-woocommerce.php
  inc/woocommerce/storefront-woocommerce-template-hooks.php
Labels: Status: Approved

#787 Hide handheld footer bar when an input is focused
  assets/css/woocommerce/woocommerce.scss
  assets/js/navigation.js
Labels: Status: Approved
