Repository woocommerce/storefront, pull requests merged in 2020-02, with the labels that each got.

#1251 All Products block: don't make sale badge transparent to avoid constrast issues
  assets/css/base/gutenberg-editor.scss
  assets/css/woocommerce/woocommerce.scss
Labels: Accessibility, Status: Needs Review

#1216 Make skip-link focusable, keyboard accessibility
  assets/css/base/_base.scss
Labels: Accessibility

#1258 Update dev dependencies to latest minor version
  .browserslistrc
  Gruntfile.js
  package-lock.json
  package.json
Labels: Status: Needs Review

#1207 Prevent indexing of add to cart link
  inc/woocommerce/storefront-woocommerce-template-functions.php
Labels: Status: Approved

#1238 fix password visiblity not showing #1236
  assets/css/woocommerce/woocommerce.scss
Labels: Type: Bug

#1257 fix untranslatable string ("or") in admin notice when WooCommerce plugin is deactivated
  inc/admin/class-storefront-plugin-install.php
Labels: Status: Needs Review

#1199 Exclude storefront/ and storefront.zip when preparing a release
  .gitignore
  Gruntfile.js
Labels: Status: Needs Review

#1187 Don't apply link styles to core components-button
  assets/css/base/_base.scss
Labels: Status: Needs Review

#1261 Customizer: Adjust footer heading and link color
  inc/customizer/class-storefront-customizer.php
Labels: Status: Needs Review

#1267 fix issue with top rated product not well aligned to the center
  assets/css/base/gutenberg-blocks.scss
  assets/css/woocommerce/woocommerce.scss
Labels: Type: Bug
