Repository woocommerce/storefront, pull requests merged in 2020-09, with the labels that each got.

#1424 Skip styling All Products Product Title if we have a font size or a color from the editor
  assets/css/woocommerce/woocommerce.scss
Labels: Type: Bug

#1453 Add icons to notices and messages
  assets/css/woocommerce/woocommerce.scss
Labels: Status: Needs Review, Type: Enhancement

#1463 reinstate phpcs php linting
  404.php
  comments.php
  composer.json
  composer.lock
  inc/admin/class-storefront-admin.php
  inc/admin/class-storefront-plugin-install.php
  inc/class-storefront.php
  inc/customizer/class-storefront-customizer.php
  inc/jetpack/class-storefront-jetpack.php
  inc/nux/class-storefront-nux-admin.php
  inc/nux/class-storefront-nux-starter-content.php
  inc/storefront-functions.php
  inc/storefront-template-functions.php
  inc/woocommerce/class-storefront-woocommerce-adjacent-products.php
  inc/woocommerce/class-storefront-woocommerce-customizer.php
  inc/woocommerce/class-storefront-woocommerce.php
  inc/woocommerce/storefront-woocommerce-template-functions.php
  inc/wordpress-shims.php
  package.json
  phpcs.xml
Labels: Status: Needs Review
