Repository woocommerce/storefront, pull requests merged in 2020-10, with the labels that each got.

#1489 👌 IMPROVE: Rename @wordpress/env commands
  CONTRIBUTING.md
  package.json
Labels: Status: Needs Review

#1481 clarify release process: release from trunk, test as needed for release risk / complexity
  docs/releases.md
Labels: Status: Needs Review

#1462 Migrate to WooRelease for automating releases
  CONTRIBUTING.md
  package.json
Labels: Status: In Progress

#1501 Fix different font sizes of category and product titles in shop page
  assets/css/woocommerce/woocommerce.scss
Labels: Type: Bug, scope: styles

#1502 Update Autoprefixer and replace grunt-postcss
  Gruntfile.js
  package-lock.json
  package.json
Labels: Status: Needs Review, Type: build

#1513 Add more specificity to wp-block-cover
  inc/customizer/class-storefront-customizer.php
Labels: Block: Cover, Priority: High, Status: Approved, Type: Bug
