Repository woocommerce/storefront, pull requests merged in 2020-05, with the labels that each got.

#1343 Rename camelCase mixins to use hyphens
  assets/css/base/_base.scss
  assets/css/sass/utils/_mixins.scss
  assets/css/woocommerce/woocommerce.scss
Labels: Status: Approved

#1344 Fix product grids selector not targeting All Products block
  assets/css/woocommerce/woocommerce.scss
Labels: Status: Approved

#1353 #1347: Remove obsolete CSS statement
  assets/css/base/icons.scss
Labels: Status: Needs Review

#1352 Add brands section to Font Awesome Library
  assets/css/base/icons.scss
Labels: Status: Needs Author Feedback, Status: Needs Review

#1359 remove testing flows doc - now in wiki
  docs/releases.md
  docs/testing.md
Labels: Status: Needs Review

#1355 add hints to explain the issue and fix in PR template
  .github/pull_request_template.md
Labels: Status: Needs Review

#1358 reinstate icons in comment list forms - edit, reply, post author
  assets/css/base/icons.scss
Labels: Status: Needs Review

#1360 update release process doc to include testing instructions & wiki
  docs/releases.md
Labels: Status: Needs Review
