Repository woocommerce/storefront, pull requests merged in 2020-07, with the labels that each got.

#1422 Fix incorrect starter content for HomePage.
  inc/nux/class-storefront-nux-starter-content.php
Labels: Status: Needs Review, Type: Bug

#1419 Merge duplicate CSS selectors
  assets/css/base/_base.scss
Labels: Type: Enhancement, scope: styles

#1428 Fix focus outline in My Account page with Firefox
  assets/css/woocommerce/woocommerce.scss
Labels: Status: Needs Review, Type: Bug, scope: styles
