Repository woocommerce/storefront, pull requests merged in 2020-08, with the labels that each got.

#1412 Add Cart and Checkout block styles
  assets/css/base/_base.scss
  inc/customizer/class-storefront-customizer.php
  inc/storefront-functions.php
Labels: Status: Needs Review

#1440 Add defensive checks for WC Cart instance
  inc/woocommerce/storefront-woocommerce-template-functions.php
Labels: Priority: High, Status: Needs Review, Type: Enhancement

#1452 Fix Product Pagination including draft product
  inc/woocommerce/class-storefront-woocommerce-adjacent-products.php
Labels: Status: Approved, Type: Bug
