Repository woocommerce/storefront, pull requests merged in 2020-11, with the labels that each got.

#1503 Install cssnano to minify CSS files
  Gruntfile.js
  package.json
Labels: Status: Needs Review

#1508 Add accent color to WC Blocks price slider
  inc/customizer/class-storefront-customizer.php
Labels: Status: Needs Review, scope: styles

#1525 Remove editor dynamic width feature
  Gruntfile.js
  assets/css/base/gutenberg-editor.scss
  assets/js/src/editor.js
  inc/class-storefront.php
  package-lock.json
  package.json
Labels: Editor, Status: Needs Review

#1534 Fix incorrect uses of `esc_attr*` and `esc_html*` picked up by WPORG checks
  comments.php
  inc/admin/class-storefront-admin.php
  inc/admin/class-storefront-plugin-install.php
  inc/storefront-template-functions.php
  inc/woocommerce/storefront-woocommerce-template-functions.php
Labels: Type: Enhancement, Type: Refactor

#1206 Add link text on cart button in handheld footer bar (fixes #1205)
  inc/woocommerce/storefront-woocommerce-template-functions.php
Labels: Accessibility
