Repository woocommerce/storefront, pull requests merged in 2021-05, with the labels that each got.

#1654 Remove Jquery Pointer Events Polyfill (PEP)
  assets/js/vendor/pep.min.js
  inc/class-storefront.php
Labels: status: needs review, type: enhancement, type: technical debt

#1674 Update build tools
  .browserslistrc
  .editorconfig
  .eslintrc.js
  .gitattributes
  .github/workflows/approved-with-labels.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/js-css-linting.yml
  .github/workflows/php-coding-standards.yml
  .gitignore
  .jshintrc
  .prettierrc.js
  .stylelintignore
  .stylelintrc
  .stylelintrc.json
  .travis.yml
  CONTRIBUTING.md
  Gruntfile.js
  README.md
  README.txt
  assets/css/base/gutenberg-blocks.scss
  assets/css/base/gutenberg-editor.scss
  assets/css/base/icons.scss
  assets/css/woocommerce/extensions/bookings.scss
  assets/css/woocommerce/extensions/brands.scss
  assets/css/woocommerce/extensions/bundles.scss
  assets/css/woocommerce/extensions/composite-products.scss
  assets/css/woocommerce/extensions/memberships.scss
  assets/css/woocommerce/extensions/photography.scss
  assets/css/woocommerce/extensions/product-recommendations.scss
  assets/css/woocommerce/extensions/product-reviews-pro.scss
  assets/css/woocommerce/extensions/ship-multiple-addresses.scss
  assets/css/woocommerce/extensions/smart-coupons.scss
  assets/css/woocommerce/extensions/wishlists.scss
  assets/css/woocommerce/woocommerce.scss
  assets/js/admin/admin.js
  assets/js/admin/customizer.js
  assets/js/admin/plugin-install.js
  assets/js/footer.js
  assets/js/homepage.js
  assets/js/navigation.js
  assets/js/skip-link-focus-fix.js
  assets/js/sticky-add-to-cart.js
  assets/js/woocommerce/extensions/brands.js
  assets/js/woocommerce/header-cart.js
  composer.json
  composer.lock
  e2e/specs/browser.test.js
  inc/nux/class-storefront-nux-starter-content.php
  inc/woocommerce/class-storefront-woocommerce-adjacent-products.php
  languages/storefront.pot
  package-lock.json
  package.json
  phpcs.xml
  style.scss
Labels: status: ready to merge

#1681 Include prettier alias as a dependency
  assets/js/sticky-add-to-cart.js
  package-lock.json
  package.json
Labels: status: ready to merge

#1690 check if Storefront_NUX_Admin_Inbox_Messages_Customize is defined bef…
  inc/nux/class-storefront-nux-admin-inbox-messages-customize.php
Labels: status: ready to merge, type: bug, type: compatibility

#1691 Image optimisation with ImageAlpha (png8+alpha) and ImageOptim.
  assets/images/admin/welcome-screen/automattic.png
  assets/images/admin/welcome-screen/child-themes.jpg
  assets/images/admin/welcome-screen/storefront-bundle-hero.png
  assets/images/customizer/controls/2cl.png
  assets/images/customizer/controls/2cr.png
  assets/images/customizer/starter-content/categories/accessories.jpg
  assets/images/customizer/starter-content/categories/hoodies.jpg
  assets/images/customizer/starter-content/categories/tshirts.jpg
  screenshot.png
Labels: category: performance, status: needs review
