Repository woocommerce/storefront, pull requests merged in 2021-08, with the labels that each got.

#1754 Removed superfluous slashes from Star and WooCommerce fonts urls
  inc/woocommerce/class-storefront-woocommerce.php
Labels: type: bug

#1755 Prevent search widget styles leaking into the Search block when added to a widget area
  assets/css/base/_base.scss
  assets/css/base/icons.scss
Labels: category: styles, status: ready to merge

#1762 Add width:auto to full width images
  assets/css/base/gutenberg-blocks.scss
Labels: type: bug, category: styles, impact: high, status: ready to merge

#1763 Remove `.gitattributes` file and add excluded files to `composer.json`
  .gitattributes
  composer.json
Labels: type: build, status: ready to merge
